// src/components/Button/Button.svelte
<script>
  import PrevIcon from '../../assets/icons/caret-left.svelte';
  import NextIcon from '../../assets/icons/caret-right.svelte';
  import link from '../../actions/link';

  /** Link for the button */
  export let href: string;
  /** Whether arrow should be backwards */
  export let back: boolean | undefined = undefined;

  const iconProps = {
    height: '0.625em',
    width: '0.625em'
  };
</script>

<style>
  .button {
    display: inline-flex;
    align-items: center;
    font-size: var(--scale-00);
    padding: 0.5em 1em;
    border-radius: var(--radius-round);
    background: var(--color-grey-100);
    color: var(--color-grey-700);
  }
</style>

<a use:link {href} class="button typeset-ui {$$props.class}">
  {#if back}
    <PrevIcon {...iconProps} />
  {/if}
  <div style="margin: 0 {!back ? '0.3em' : 0} 0 {back ? '0.3em' : 0}">
    <slot />
  </div>
  {#if !back}
    <NextIcon {...iconProps} />
  {/if}
</a>

// src/components/Button/index.tsx
import { css } from '@emotion/react';
import { ReactNode } from 'react';
import { ReactComponent as PrevIcon } from '../../assets/icons/caret-left.svg';
import { ReactComponent as NextIcon } from '../../assets/icons/caret-right.svg';
import { Link } from '../Link';

export type ButtonProps = {
  /** Link for the button */
  href: string;
  /** Whether arrow should be backwards */
  back?: boolean;
  children: ReactNode;
};

const styles = {
  button: css`
    display: inline-flex;
    align-items: center;
    font-size: var(--scale-00);
    padding: 0.5em 1em;
    line-height: 1;
    border-radius: var(--radius-round);
    background: var(--color-grey-100);
    color: var(--color-grey-700);
  `,
  icon: css`
    fill: currentColor;
    height: 0.625em;
    width: 0.625em;
  `
};

/**
 * Simple button component
 */
export function Button({ href, back, children, ...props }: ButtonProps) {
  return (
    <Link css={styles.button} href={href} {...props}>
      {back && <PrevIcon css={styles.icon} />}
      <div
        css={css`
          margin: 0 ${!back ? '0.3em' : 0} 0 ${back ? '0.3em' : 0};
        `}
      >
        {children}
      </div>
      {!back && <NextIcon css={styles.icon} />}
    </Link>
  );
}
