// src/routes/collections/[uid].svelte
<script context="module">
  export const load: Load = async ({ page }) => {
    const { data } = await queryAt('my.collection.uid', page.params.uid, {
      fetchLinks: ['photo.photo', 'photo.title']
    });

    return {
      props: { data }
    };
  };
</script>

<script>
  import type { Load } from '@sveltejs/kit';
  import Gallery from 'svelte-gallery';
  import Meta from 'svelte-meta';
  import type { Collection } from '../../../@types/_generated/prismic';
  import Button from '../../components/Button/Button.svelte';
  import Footer from '../../components/Footer/Footer.svelte';
  import GalleryImage from '../../components/GalleryImage/GalleryImage.svelte';
  import Header from '../../components/Header/Header.svelte';
  import SectionHeader from '../../components/SectionHeader/SectionHeader.svelte';
  import { plaintext, queryAt } from '../../lib/prismic';
  import { media } from '../../lib/stores';
  import { customMedia } from '../../styles/breakpoints.json';

  export let data: Collection;
</script>

<Meta
  title={data.meta_title}
  description={data.meta_description}
  image={data.meta_cover.url}
/>

<Header />

<SectionHeader title={plaintext(data.name)} large>
  <Button slot="action" back href="/">Back</Button></SectionHeader
>
<Gallery
  gutter={$media['--desktop'] ? 12 : 16}
  images={data.photos
    ? data.photos.map(({ photo }) => {
        const { url, dimensions } = photo?.data.photo;

        return {
          uid: photo?.uid,
          src: url,
          sizes: [
            `${customMedia['--mobile']} 50vw`,
            `${customMedia['--tablet']} 33vw`,
            `100vw`
          ],
          alt: photo?.data.title,
          ...dimensions
        };
      })
    : []}
  rowHeight={420}
  imageComponent={GalleryImage}
/>

<Footer />

// src/pages/collections/[uid].tsx
import { css } from '@emotion/react';
import { GetStaticPaths, GetStaticProps } from 'next';
import { Collection } from '../../../@types/_generated/prismic';
import { Button } from '../../components/Button';
import { Footer } from '../../components/Footer';
import { Header } from '../../components/Header';
import { Img } from '../../components/Img';
import { Link } from '../../components/Link';
import { Meta } from '../../components/Meta';
import { SectionHeader } from '../../components/SectionHeader';
import { getAll, getUid, plaintext, resolveDocument } from '../../lib/prismic';
import { desktop, mobile, tablet } from '../../styles/breakpoints';

const styles = {
  wrapper: css`
    display: grid;
    grid-template-columns: var(--grid-content);
  `,
  gallery: css`
    grid-column: 1 / -1;
    @media (min-width: ${desktop}) {
      grid-column: 2 / span 10;
    }
  `,
  images: css`
    columns: 1;
    column-gap: var(--grid-gap);
    @media (min-width: ${mobile}) {
      columns: 2;
    }
    @media (min-width: ${tablet}) {
      columns: 3;
    }
  `,
  image: css`
    display: inline-block;
    padding-bottom: var(--grid-gap);
    /* HACK because CSS */
    margin-bottom: -4px;
  `
};

/**
 * Collection page
 */
export default function CollectionPage({ data }: { data: Collection }) {
  if (!data) {
    return null;
  }

  return (
    <>
      <Meta
        title={data.meta_title}
        description={data.meta_description}
        cover={data.meta_cover.url}
      />

      <Header />

      <div css={styles.wrapper}>
        <section css={styles.gallery}>
          <SectionHeader
            title={plaintext(data.name)}
            large
            action={
              <Button back href="/">
                Back
              </Button>
            }
          />
          <div css={styles.images}>
            {data.photos?.map(({ photo }: any) => (
              <Link
                href={resolveDocument(photo)}
                css={styles.image}
                key={photo.uid}
              >
                <Img
                  prismic={photo.data.photo}
                  alt={photo.data.title}
                  sizes={`(max-width: ${mobile}) 100vw, (max-width: ${tablet}) 50vw, 33vw`}
                />
              </Link>
            ))}
          </div>
        </section>
      </div>

      <Footer />
    </>
  );
}

/** Page generation */
export const getStaticPaths: GetStaticPaths = async (context) => {
  const documents = await getAll('collection', context);

  return {
    paths: documents.map(({ uid }: any) => ({
      params: {
        uid
      }
    })),
    fallback: true
  };
};

/** Page data */
export const getStaticProps: GetStaticProps = async (context) => {
  const data = await getUid(
    'collection',
    context.params?.uid as string,
    context,
    { fetchLinks: ['photo.photo', 'photo.title'] }
  );

  return !!data
    ? {
        props: {
          data,
          preview: context.preview || null
        }
      }
    : {
        notFound: true
      };
};
