// src/components/Anchor/index.tsx
import { css } from '@emotion/react';
import { Link, LinkProps } from '../Link';
import { ReactComponent as ArrowIcon } from '../../assets/icons/arrow.svg';

const styles = {
  link: css`
    display: inline-flex;
    align-items: center;
    color: var(--color-primary);
  `,
  icon: css`
    fill: currentColor;
    width: 1em;
    height: 1em;
    margin-left: 0.5em;
    transform: translateY(5%);
  `
};

/**
 * Anchor style button
 */
export function Anchor({ children, ...props }: LinkProps) {
  return (
    <Link css={styles.link} {...props}>
      {children}
      <ArrowIcon css={styles.icon} />
    </Link>
  );
}

// src/components/Anchor/Anchor.svelte
<!--
  @component
  Anchor CTA
-->
<script>
  import link from '../../actions/link';
  import Arrow from '../../assets/icons/arrow-right.svelte';

  /** URL to link to */
  export let href: string;
</script>

<style>
  .anchor {
    display: inline-flex;
    align-items: center;
    color: var(--color-primary);
  }

  .label {
    margin-right: 0.5em;
    transform: translateY(-2%);
  }
</style>

<a use:link {href} class="anchor typeset-ui {$$props.class}">
  <div class="label">
    <slot />
  </div>
  <Arrow height="0.85em" width="0.85em" />
</a>
