// src/components/Header/index.tsx
import { css } from '@emotion/react';
import { useState } from 'react';
import { HamburgerIcon } from 'react-hamburger-icon';
import { Overlay } from 'react-portal-overlay';
import { ReactComponent as MailIcon } from '../../assets/icons/mail.svg';
import { ReactComponent as InstagramIcon } from '../../assets/icons/instagram.svg';
import { ReactComponent as TwitterIcon } from '../../assets/icons/twitter.svg';
import { mobile, tablet } from '../../styles/breakpoints';
import { pageGrid } from '../../styles/mixins';
import { heading2 } from '../../styles/typesets';
import { Link } from '../Link';

const styles = {
  header: css`
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: var(--spacing-6);
    font-size: var(--scale-0);
    line-height: 1;
    @media (min-width: ${tablet}) {
      margin-bottom: var(--spacing-7);
    }
  `,
  logo: css`
    font-weight: var(--font-weight-bold);
    font-size: var(--scale-1);
  `,
  nav: css`
    display: flex;
    align-items: center;
    & > *:not(:last-of-type) {
      margin-right: 1.5rem;
    }
    @media (max-width: ${mobile}) {
      display: none;
    }
  `,
  navIcon: css`
    fill: currentColor;
    width: var(--scale-3);
    height: var(--scale-3);
    @media (min-width: ${mobile}) {
      width: 1em;
      height: 1em;
    }
  `,

  hamburger: css`
    z-index: var(--layer-top);
    @media (min-width: ${mobile}) {
      display: none;
    }
  `,
  mobMenu: css`
    ${pageGrid}
    height: 100%;
    padding-top: var(--spacing-5);
    align: space-between;
    background: white;
  `,
  mobSocials: css`
    display: flex;
    align-items: center;
    justify-content: center;
    & > * {
      margin: 0 1.5rem;
    }
  `
};

/**
 * Global header for the site
 */
export function Header(props: any) {
  const [mobNavOpen, setMobNavOpen] = useState(false),
    closeMenu = () => setMobNavOpen(false);

  return (
    <>
      <header css={styles.header} {...props}>
        <Link href="/">
          <h1 css={styles.logo}>Madeleine Ostoja</h1>
        </Link>
        <nav css={styles.nav}>
          <Link href="https://twitter.com/madeleineostoja">
            <TwitterIcon css={styles.navIcon} />
          </Link>
          <Link href="https://instagram.com/filmic__">
            <InstagramIcon css={styles.navIcon} />
          </Link>
          <Link href="mailto:madi@madeleineostoja.com">
            <MailIcon css={styles.navIcon} />
          </Link>
          <Link href="/about">About</Link>
          <Link href="https://madi.darkroom.tech">Prints</Link>
        </nav>
        <HamburgerIcon
          css={styles.hamburger}
          open={mobNavOpen}
          onClick={() => setMobNavOpen(!mobNavOpen)}
        />
      </header>

      <Overlay open={mobNavOpen} closeOnEsc={true} onClose={closeMenu}>
        <div css={styles.mobMenu}>
          <nav>
          <Link
              css={heading2}
              onClick={closeMenu}
              href="/about"
            >
              About
            </Link>
            <Link
              css={heading2}
              onClick={closeMenu}
              href="https://madi.darkroom.tech"
            >
              Prints
            </Link>
          </nav>
          <div css={styles.mobSocials}>
            <Link
              onClick={closeMenu}
              href="https://twitter.com/madeleineostoja"
            >
              <TwitterIcon css={styles.navIcon} />
            </Link>
            <Link onClick={closeMenu} href="https://instagram.com/filmic__">
              <InstagramIcon css={styles.navIcon} />
            </Link>
            <Link onClick={closeMenu} href="mailto:madi@madeleineostoja.com">
              <MailIcon css={styles.navIcon} />
            </Link>
          </div>
        </div>
      </Overlay>
    </>
  );
}

// src/components/Header/Header.svelte
<script>
  import Hamburger from 'svelte-hamburger';
  import { fade } from 'svelte/transition';
  import link from '../../actions/link';
  import InstagramIcon from '../../assets/icons/instagram.svelte';
  import MailIcon from '../../assets/icons/mail.svelte';
  import TwitterIcon from '../../assets/icons/twitter.svelte';

  let mobNavOpen = false;

  function closeMenu() {
    mobNavOpen = false;
  }
</script>

<style>
  header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: var(--spacing-6);
    font-size: var(--scale-0);
    @media (--tablet) {
      margin-bottom: var(--spacing-7);
    }
  }

  .logo {
    font-weight: var(--font-weight-bold);
    font-size: var(--scale-1);
  }

  .nav {
    display: none;
    align-items: center;
    & > *:not(:last-of-type) {
      margin-right: 1.5rem;
    }
    @media (--mobile) {
      display: flex;
    }
  }

  .navIcon :global(svg) {
    fill: currentColor;
    width: var(--scale-3);
    height: var(--scale-3);
    @media (--mobile) {
      width: 1em;
      height: 1em;
    }
  }

  .hamburger {
    z-index: var(--layer-top);
    cursor: pointer;
    @media (--mobile) {
      display: none;
    }
  }

  .mobMenu {
    position: fixed;
    top: 0;
    left: 0;
    height: 100%;
    width: 100%;
    padding-top: var(--spacing-5);
    align: space-between;
    background: white;
    z-index: var(--layer-5);
  }

  .mobNavLink {
    margin-bottom: 1em;
  }

  .mobSocials {
    display: flex;
    align-items: center;
    justify-content: center;
    & > * {
      margin: 0 1.5rem;
    }
  }
</style>

<header class="typeset-ui {$$props.class}">
  <a use:link href="/">
    <h1 class="logo">Madeleine Ostoja</h1>
  </a>
  <nav class="nav">
    <a
      use:link
      href="https://twitter.com/madeleineostoja"
      aria-label="Twitter"
      class="navIcon"
    >
      <TwitterIcon />
    </a>
    <a
      use:link
      href="https://instagram.com/madeleineostoja"
      aria-label="Instagram"
      class="navIcon"
    >
      <InstagramIcon />
    </a>
    <a
      use:link
      href="mailto:madi@madeleineostoja.com"
      aria-label="Email"
      class="navIcon"
    >
      <MailIcon />
    </a>
    <a use:link href="/about">About</a>
    <a use:link href="https://madi.darkroom.tech">Prints</a>
  </nav>
  <div class="hamburger">
    <Hamburger open={mobNavOpen} on:click={() => (mobNavOpen = !mobNavOpen)} />
  </div>
</header>

{#if mobNavOpen}
  <div class="mobMenu pageGrid" transition:fade={{ duration: 150 }}>
    <nav>
      <a
        use:link
        class="mobNavLink typeset-h2"
        on:click={closeMenu}
        href="/about"
      >
        About
      </a>
      <a
        use:link
        class="mobNavLink typeset-h2"
        on:click={closeMenu}
        href="https://madi.darkroom.tech"
      >
        Prints
      </a>
    </nav>
    <div class="mobSocials">
      <a
        use:link
        on:click={closeMenu}
        href="https://twitter.com/madeleineostoja"
        class="navIcon"
        aria-label="Twitter"
      >
        <TwitterIcon />
      </a>
      <a
        use:link
        on:click={closeMenu}
        href="https://instagram.com/madeleineostoja"
        class="navIcon"
        aria-label="Instagram"
      >
        <InstagramIcon />
      </a>
      <a
        use:link
        on:click={closeMenu}
        href="mailto:madi@madeleineostoja.com"
        class="navIcon"
        aria-label="Email"
      >
        <MailIcon />
      </a>
    </div>
  </div>
{/if}
